service: typescript-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  hello:
    handler: dist/hello.handler
    events:
      - http:
          path: hello
          method: GET
          cors: true
